[config]
reload_apps = true
set_wallpaper = false  # Let hyprpaper handle this

[templates.colors]
input_path = "~/.config/matugen/templates/colors.json"
output_path = "~/.config/quickshell/colors.json"